name: build-extension
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: start X server
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
    - run: npm run package
    - uses: actions/upload-artifact@v3
      with:
        name: 'sudu-vscode-clangd.vsix'
        path: '*.vsix'
